import streamlit as st
import requests
import uuid
import re
from html import unescape
from pathlib import Path

from dotenv import dotenv_values
from backend.app.config import settings
from backend.app.logging_config import configure_local_logging


API_BASE_URL = "http://localhost:8000"
PROJECT_ROOT = Path(__file__).resolve().parents[2]

if settings.is_on_prem_deployment:
    configure_local_logging("frontend")


def clean_text(value: str) -> str:
    if not value:
        return ""
    text = unescape(value)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def extract_root_cause_analysis(bug: dict) -> str:
    metadata = bug.get("metadata", {}) or {}
    rca = metadata.get("root_cause_analysis", "")
    if rca:
        return clean_text(str(rca))

    description = bug.get("description", "")
    marker = "Root Cause Analysis:"
    if marker in description:
        return clean_text(description.split(marker, 1)[1])

    return ""


def extract_relevant_snippet(content: str, query: str) -> str:
    """Return the wiki block most relevant to the query based on keyword overlap."""
    if not content or not query:
        return content
    blocks = [b.strip() for b in re.split(r'\n\s*\n', content) if b.strip()]
    if len(blocks) <= 1:
        return content
    stopwords = {'the', 'a', 'an', 'is', 'in', 'to', 'and', 'or', 'of', 'with', 'for', 'on', 'at'}
    query_words = set(re.findall(r'\w+', query.lower())) - stopwords
    best_idx, best_score = 0, -1
    for i, block in enumerate(blocks):
        words = set(re.findall(r'\w+', block.lower()))
        score = len(query_words & words)
        if score > best_score:
            best_score, best_idx = score, i
    if best_score == 0:
        return blocks[0]
    # Include preceding block (usually the section header) for context
    start = max(0, best_idx - 1)
    return '\n\n'.join(blocks[start: best_idx + 2])


def extract_suggested_fix(bug: dict) -> str:
    metadata = bug.get("metadata", {}) or {}
    fix = metadata.get("suggested_fix", "")
    return clean_text(str(fix)) if fix else ""


def get_index_status() -> dict:
    try:
        resp = requests.get(f"{API_BASE_URL}/api/admin/index-status", timeout=10)
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        return {"_error": str(e)}


def get_runtime_info() -> dict:
    try:
        resp = requests.get(f"{API_BASE_URL}/api/admin/runtime-info", timeout=10)
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        return {"_error": str(e)}


def get_workspace_deployment_mode() -> str:
    """Read the intended workspace mode without exposing environment secrets."""
    configured_mode = dotenv_values(PROJECT_ROOT / ".env").get("DEPLOYMENT_MODE", "azure")
    return str(configured_mode).strip().lower() or "azure"


def format_retrieval_backend(retrieval_backend: str) -> str:
    return {
        "azure_ai_search": "Azure AI Search",
        "local_vector_index": "local vector index",
    }.get(retrieval_backend, retrieval_backend.replace("_", " "))


def trigger_refresh() -> dict:
    resp = requests.post(f"{API_BASE_URL}/api/admin/refresh", timeout=300)
    resp.raise_for_status()
    return resp.json()


def get_user_id() -> str:
    if "user_id" not in st.session_state:
        st.session_state.user_id = f"streamlit-{uuid.uuid4().hex[:8]}"
    return st.session_state.user_id


def solve_issue(query: str) -> dict:
    response = requests.post(
        f"{API_BASE_URL}/api/issues/solve",
        json={
            "user_id": get_user_id(),
            "message": query,
        },
        timeout=180,
    )
    response.raise_for_status()
    return response.json()


def render_model_info(result: dict) -> None:
    """Show the retrieval backend that supplied the current result."""
    model_info = result.get("model_info") or {}
    runtime_info = st.session_state.get("runtime_info", {})
    retrieval_backend = runtime_info.get("retrieval_backend") or model_info.get("retrieval_backend")

    if retrieval_backend:
        st.caption(f"Knowledge retrieval: {format_retrieval_backend(retrieval_backend)}")


def render_result(result: dict, query: str = "") -> None:
    st.subheader("Solution")

    # A browser session can retain a result while the backend is replaced.
    # Do not display metadata from the previous deployment as if it came from
    # the backend currently serving this page.
    if isinstance(result, dict):
        result_mode = (result.get("model_info") or {}).get("deployment_mode")
        runtime_mode = (st.session_state.get("runtime_info") or {}).get("deployment_mode")
        if result_mode and runtime_mode and result_mode != runtime_mode:
            st.warning(
                "This result was generated by a previous backend configuration and has been cleared. "
                "Submit the issue again to use the active backend."
            )
            st.session_state.pop("last_result", None)
            st.session_state.pop("last_query", None)
            return

    # Friendly handling when the backend indicates no confident matches
    # Either the backend may return an explicit sentinel, or all result lists may be empty.
    is_sentinel = isinstance(result, str) and result == "no match"
    empty_body = (
        not result.get("similar_bugs") and
        not result.get("relevant_wiki") and
        not result.get("root_causes") and
        not result.get("suggested_fixes")
    )
    if not is_sentinel:
        render_model_info(result)

    if is_sentinel or empty_body:
        st.warning("No matching bug or wiki entry was found. I can still provide a general recommendation, but there is no strong historical match to cite.")
        st.markdown(result.get("analysis", "No analysis returned."))
        return

    st.markdown(result.get("analysis", "No analysis returned."))

    # Show the strongest candidate bugs. This keeps the user in control when the
    # semantic match is close but the title wording is not exact.
    all_similar = result.get("similar_bugs", [])
    similar_bugs = all_similar[:3] if all_similar else []
    if similar_bugs:
        st.subheader("Similar Issues")
        for idx, bug in enumerate(similar_bugs, 1):
            title = bug.get("title", "Untitled")
            score = bug.get("similarity_score", 0.0)
            source = bug.get("source", "local_vector_index")
            st.markdown(f"{idx}. **{title}** ({score:.2f}) — Source: {source.replace('_', ' ').title()}")

            bug_description = clean_text(str(bug.get("description", "")))
            root_cause_analysis = extract_root_cause_analysis(bug)
            suggested_fix = extract_suggested_fix(bug)

            if bug_description or root_cause_analysis or suggested_fix:
                with st.expander(f"Details: {title}"):
                    if bug_description:
                        st.markdown(f"**Description:** {bug_description}")
                    if root_cause_analysis:
                        st.markdown(f"**Root Cause Analysis:** {root_cause_analysis}")
                    if suggested_fix:
                        st.markdown(f"**Suggested Fix (from ADO):** {suggested_fix}")

    wiki_with_content = [p for p in result.get("relevant_wiki", []) if p.get("content", "").strip()]
    if wiki_with_content:
        st.subheader("Relevant Wiki")
        for page in wiki_with_content:
            title = page.get("title", "Untitled")
            score = page.get("similarity_score", 0.0)
            source = page.get("source", "local_vector_index")
            content = page.get("content", "").strip()
            url = page.get("url", "")
            snippet = extract_relevant_snippet(content, query) if query else content
            st.markdown(f"- **{title}** ({score:.2f}) — Source: {source.replace('_', ' ').title()}")
            with st.expander(f"Lessons from: {title}"):
                st.markdown(snippet)
                if url:
                    st.markdown(f"[View in Azure DevOps Wiki]({url})")

    root_causes = result.get("root_causes", [])
    if root_causes:
        st.subheader("Root Causes")
        for cause in root_causes:
            description = cause.get("description", "")
            confidence = cause.get("confidence", 0.0)
            st.markdown(f"- {description} ({confidence:.0%})")

    suggested_fixes = result.get("suggested_fixes", [])
    if suggested_fixes:
        st.subheader("Suggested Fixes")
        priority_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}
        for i, fix in enumerate(suggested_fixes, 1):
            description = fix.get("description", "")
            priority = fix.get("priority", "medium")
            steps = fix.get("steps", [])
            badge = priority_emoji.get(priority, "🟡")
            with st.expander(f"{badge} **Fix {i}:** {description}  `{priority.upper()}`", expanded=(i == 1)):
                if steps:
                    for j, step in enumerate(steps, 1):
                        st.markdown(f"**{j}.** {step}")



st.title("ErrorLens - AI-Powered Issue Advisor")

# ── Sidebar: Azure DevOps data refresh ──────────────────────────────────────
with st.sidebar:
    st.header("🔄 Knowledge Base")

    runtime = get_runtime_info()
    if "_error" in runtime:
        st.warning(f"Could not read backend runtime status: {runtime['_error']}")
    else:
        st.session_state.runtime_info = runtime
        backend_instance = f"{runtime.get('process_id')}:{runtime.get('started_at')}"
        previous_instance = st.session_state.get("backend_instance")
        if previous_instance and previous_instance != backend_instance:
            st.session_state.pop("last_result", None)
            st.session_state.pop("last_query", None)
            st.info("Backend restarted — cleared results from the previous backend session.")
        st.session_state.backend_instance = backend_instance

        running_mode = runtime.get("deployment_mode", "unknown")
        expected_mode = get_workspace_deployment_mode()
        st.caption(
            f"Backend: {running_mode.title()} mode · "
            f"Retrieval: {format_retrieval_backend(runtime.get('retrieval_backend', 'unknown'))} · "
            f"Generation: {runtime.get('chat_provider', 'unknown').replace('_', ' ').title()}"
        )
        st.caption(f"Process {runtime.get('process_id')} · started {runtime.get('started_at')}")
        if running_mode != expected_mode:
            st.error(
                f"Backend is running in {running_mode} mode, but this workspace is configured for "
                f"{expected_mode} mode. Restart the backend to apply the workspace configuration."
            )

    status = get_index_status()
    if "_error" in status:
        st.warning(f"⚠️ Could not reach backend: {status['_error']}")
    else:
        age = status.get("oldest_age_hours")
        stale = status.get("stale", False)
        if age is not None:
            age_label = f"{age:.1f}h ago"
            if stale:
                st.warning(f"⚠️ Index is stale — last synced {age_label}")
            else:
                st.success(f"✅ Index is fresh — last synced {age_label}")
        bugs_info = status.get("bugs_index", {})
        wiki_info = status.get("wiki_index", {})
        if bugs_info.get("exists"):
            st.caption(f"Bugs index: {bugs_info.get('size_kb', '?')} KB")
        if wiki_info.get("exists"):
            st.caption(f"Wiki index: {wiki_info.get('size_kb', '?')} KB")

    if st.button("🔃 Refresh from Azure DevOps", use_container_width=True):
        with st.spinner("Fetching latest bugs & wiki from Azure DevOps… this may take a minute."):
            try:
                result = trigger_refresh()
                if result.get("success"):
                    st.rerun()
                else:
                    st.error("Refresh completed with errors:")
                    if result.get("bugs_error"):
                        st.code(result["bugs_error"], language="text")
                    if result.get("wiki_error"):
                        st.code(result["wiki_error"], language="text")
            except requests.RequestException as exc:
                st.error(f"Refresh failed: {exc}")

    st.caption("Auto-refresh runs every 48 hours on server startup.")
# ────────────────────────────────────────────────────────────────────────────

st.markdown("""
An intelligent system that connects to Azure DevOps to learn from past bugs and wiki knowledge,
preventing and solving development issues faster.
""")

# Input for user query
with st.form("issue_advice_form", clear_on_submit=False):
    user_query = st.text_input("Describe your development issue:")
    get_advice = st.form_submit_button("🔍 Get Issue Advice")
result_placeholder = st.empty()

if get_advice:
    if user_query:
        # Clear any cached result immediately so stale data is never shown
        st.session_state.pop("last_result", None)
        st.session_state["last_query"] = user_query
        with result_placeholder.container():
            st.subheader("Solution")
            st.info(f"Analyzing '{user_query}'...")
        try:
            with st.spinner("Analyzing issue..."):
                st.session_state.last_result = solve_issue(user_query)
        except requests.HTTPError as exc:
            detail = exc.response.text if exc.response is not None else str(exc)
            st.error(f"Backend request failed: {detail}")
        except requests.RequestException as exc:
            st.error(f"Could not reach backend at {API_BASE_URL}: {exc}")
    else:
        st.warning("Please enter a query.")

if "last_result" in st.session_state:
    with result_placeholder.container():
        render_result(st.session_state.last_result, st.session_state.get("last_query", ""))
else:
    with result_placeholder.container():
        st.subheader("Solution")
        st.write("Submit an issue to see analysis results.")
