from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import datetime

doc = Document()

# Styles
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(11)


def heading(text, level=1):
    return doc.add_heading(text, level=level)


def para(text):
    return doc.add_paragraph(text)


def bullet(text, bold_prefix=None):
    p = doc.add_paragraph(style='List Bullet')
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        p.add_run(text)
    else:
        p.add_run(text)


def add_table(rows, header=None):
    t = doc.add_table(rows=len(rows) + (1 if header else 0), cols=2)
    t.style = 'Table Grid'
    if header:
        for i, h in enumerate(header):
            cell = t.rows[0].cells[i]
            cell.text = h
            run = cell.paragraphs[0].runs[0]
            run.bold = True
            run.font.color.rgb = RGBColor(255, 255, 255)
            tc = cell._tc
            tcPr = tc.get_or_add_tcPr()
            shd = OxmlElement('w:shd')
            shd.set(qn('w:fill'), '2E75B6')
            shd.set(qn('w:val'), 'clear')
            tcPr.append(shd)
    for i, (c1, c2) in enumerate(rows):
        row = t.rows[i + (1 if header else 0)]
        row.cells[0].text = c1
        row.cells[1].text = c2


# Title
title = doc.add_heading('ErrorLens — End User Functionality Guide', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
for run in title.runs:
    run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

date_str = datetime.date.today().strftime('%B %d, %Y')
date_para = doc.add_paragraph('Generated: ' + date_str)
date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_paragraph()

# 1. Overview
heading('1. Overview')
para(
    'ErrorLens is an AI-powered development issue solver that connects to Azure DevOps '
    'to learn from past bugs and wiki knowledge, helping development teams prevent and '
    'resolve issues faster. Users interact through a web-based UI or a REST API.'
)
doc.add_paragraph()

# 2. Access Points
heading('2. Access Points')
add_table([
    ('Web UI (Streamlit)',    'http://localhost:8501'),
    ('REST API Endpoint',     'POST http://localhost:8000/api/issues/solve'),
    ('Interactive API Docs',  'http://localhost:8000/docs'),
], header=['Interface', 'URL / Details'])
doc.add_paragraph()

# 3. Core Functionality
heading('3. Core User Functionality')
para(
    'The user enters a free-text description of a development issue and clicks "Solve Issue". '
    'The system returns a comprehensive analysis composed of five sections:'
)
doc.add_paragraph()

heading('3.1  AI Analysis Summary', level=2)
para(
    'A natural language paragraph explaining the issue, its likely context, and what to '
    'investigate — generated by GPT-4o-mini via the Recommendation Agent.'
)
doc.add_paragraph()

heading('3.2  Similar Past Bugs', level=2)
para('The highest-scoring bug ticket retrieved from Azure DevOps using semantic vector search. Displayed with:')
bullet('Bug title and similarity score')
bullet('Expandable detail panel containing:')
bullet('    Description from ADO')
bullet('    Root Cause Analysis (from ADO metadata)')
bullet('    Suggested Fix (from ADO metadata)')
doc.add_paragraph()

heading('3.3  Relevant Wiki Knowledge', level=2)
para(
    'The most semantically relevant section from the Azure DevOps Lessons Learned wiki. Displayed with:'
)
bullet('Section title and similarity score')
bullet('Expandable panel with the most relevant content snippet')
bullet('Direct link to the full page in Azure DevOps')
doc.add_paragraph()

heading('3.4  Root Causes', level=2)
para(
    'A list of probable root causes ranked by confidence percentage '
    '(e.g. "Null string handling not validated — 80%").'
)
doc.add_paragraph()

heading('3.5  Suggested Fixes', level=2)
para('Step-by-step remediation recommendations, each tagged with a priority level:')
add_table([
    ('High (Red)',    'Critical fixes that must be applied immediately'),
    ('Medium (Yellow)', 'Important improvements to prevent recurrence'),
    ('Low (Green)',   'Optional enhancements and best practices'),
], header=['Priority', 'Description'])
para('Each fix is expandable and displays numbered action steps.')
doc.add_paragraph()

# 4. Agent Pipeline
heading('4. How It Works (Agent Pipeline)')
para('Behind every query, five AI agents collaborate in sequence:')
add_table([
    ('Bug Analysis Agent',
     'Searches ADO work items using OpenAI embeddings + cosine similarity'),
    ('Wiki Knowledge Agent',
     'Searches wiki sections using semantic vector search; returns top-1 highest-scoring result'),
    ('Integration Context Agent',
     'Identifies affected modules, APIs, dependencies, and external services via keyword analysis'),
    ('Recommendation Agent',
     'Calls GPT-4o-mini to generate root causes and fix steps from aggregated context'),
    ('Orchestrator Agent',
     'LangGraph StateGraph that coordinates all agents and assembles the final response'),
], header=['Agent', 'Role'])
doc.add_paragraph()

# 5. Data Sources
heading('5. Data Sources')
add_table([
    ('Azure DevOps Work Items',
     'Past bug tickets used for similarity matching'),
    ('Azure DevOps Wiki',
     'Lessons Learned pages indexed as section-level vectors'),
    ('OpenAI text-embedding-3-small',
     'Converts text to 1536-dimensional vectors for semantic search'),
    ('OpenAI GPT-4o-mini',
     'Generates analysis, root causes, and fix suggestions'),
    ('Local NumPy Index',
     'Stores and searches embeddings (bugs_embeddings.npy, wiki_embeddings.npy)'),
], header=['Source', 'Purpose'])
doc.add_paragraph()

# Save
out_path = 'docs/ErrorLens_User_Functionality_Guide.docx'
doc.save(out_path)
print('Saved:', out_path)
